### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Sephirox** [NekoNova/ClearVoyanceEx#1]
Settings not working on /cv only /cv b toogle works.
Would be nice to have a way to test the addon/as well as make it appear permanently to move it and then lock it so it is not affected by mouse movements.

**Comment by NekoNova** [comment]
Clearvoyance never had any settings. The only supported option was indeed the **b** or **background** toggle.

I can build in a settings windows, but then I need to have a list of all the settings you'd like to be changed. The Addon itself doesn't give much for configuration options as it only hooks in on the CC events.

**Comment by Sephirox** [comment]
The new update works awesome for allowing one to move the addon window, it still would be nice for a way to lock it in place.

One thing that does not work is the Dissorient function, aside from that awesome work.

**Comment by NekoNova** [comment]
noted, will sort it out when I have time.

**Comment by Sephirox** [comment]
Seems the only issue now is /cv b is not saving, I have to /cv b to turn off the background on every log in

**Comment by Sephirox** [comment]
New update seems to have broken the /cv b cmd, is not working anymore.
